steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ingestor', './ingest' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/leader-election', './election' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/transcriber', './transcribe' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/reviewer', './reviewer' ]
    waitFor: ['-']

images: [
  'gcr.io/$PROJECT_ID/ingestor',
  'gcr.io/$PROJECT_ID/leader-election',
  'gcr.io/$PROJECT_ID/transcriber',
  'gcr.io/$PROJECT_ID/reviewer'
]

