steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/subtitling-ingest', './ingest' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/leader-elector', './election' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/subtitling-transcribe', './transcribe' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/subtitling-editor', './ui' ]
    waitFor: ['-']

images: [
  'eu.gcr.io/$PROJECT_ID/subtitling-ingest',
  'eu.gcr.io/$PROJECT_ID/leader-elector',
  'eu.gcr.io/$PROJECT_ID/subtitling-transcribe',
  'eu.gcr.io/$PROJECT_ID/subtitling-editor'
]

