apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-deployment
spec:
  selector:
    matchLabels:
      app: editor
  replicas: 1
  template:
    metadata:
      labels:
        app: editor
        dummy: test
    spec:
      containers:
        - name: ingestor
          image: eu.gcr.io/jtgcp-subtitles/subtitling-editor:latest
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.73.51.12
            - --host=0.0.0.0
            - --id=$(PODNAME)
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: editor-service
spec:
  selector:
    app: editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer