apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-deployment
spec:
  selector:
    matchLabels:
      app: editor
  replicas: 2
  template:
    metadata:
      labels:
        app: editor
        dummy: test2
    spec:
      containers:
        - name: ingestor
          image: eu.gcr.io/jtgcp-subtitles/subtitling-editor:latest
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.226.1.220
            - --host=0.0.0.0
            - --id=$(PODNAME)
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: editor-service
spec:
  selector:
    app: editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP