apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor-deployment
spec:
  selector:
    matchLabels:
      app: ingestor
  replicas: 2
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: gcr.io/pub-2451/ingestor:latest
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.221.13.124
            - --host=0.0.0.0
            - --port=8080
            - --id=$(PODNAME)
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ingestor-service
spec:
  selector:
    app: ingestor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP
