apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewer-deployment
spec:
  selector:
    matchLabels:
      app: reviewer
  replicas: 2
  template:
    metadata:
      labels:
        app: reviewer
        dummy: test2
    spec:
      containers:
        - name: reviewer
          image: eu.gcr.io/live-captioning-test2/reviewer:latest
          imagePullPolicy: Always
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.224.187.124
            - --host=0.0.0.0
            - --id=$(PODNAME)
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reviewer-service
spec:
  selector:
    app: editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: ClientIP
