apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election
  labels:
    app: leader-election

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: leader-election
  labels:
    app: leader-election
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: leader-election
  labels:
    app: leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election
subjects:
  - name: leader-election
    namespace: default
    kind: ServiceAccount

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber-deployment
spec:
  selector:
    matchLabels:
      app: transcriber
  replicas: 2
  template:
    metadata:
      labels:
        app: transcriber
        dummy: test3
    spec:
      serviceAccountName: leader-election
      containers:
        - name: leader-election
          image: eu.gcr.io/jtgcp-subtitles/leader-elector:latest
          imagePullPolicy: Always
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --lockName=electionlock
            - --lockNamespace=default
            - --id=$(PODNAME)
            - --port=4040
            - --logtostderr=true
        - name: transcriber
          image: eu.gcr.io/jtgcp-subtitles/subtitling-transcribe:latest
          imagePullPolicy: Always
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --redisHost=10.226.1.220
            - --electionID=$(PODNAME)
            - --encoding=LINEAR16
            - --sampleRate=16000
            - --channels=1
            - --lang=en-US
#            - --leaderOnly=false
