apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election
  labels:
    app: leader-election

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: leader-election
  labels:
    app: leader-election
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: leader-election
  labels:
    app: leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-election
subjects:
  - name: leader-election
    namespace: default
    kind: ServiceAccount

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber-deployment
spec:
  selector:
    matchLabels:
      app: transcriber
  replicas: 2
  template:
    metadata:
      labels:
        app: transcriber
        dummy: test4
    spec:
      serviceAccountName: leader-election
      containers:
        - name: leader-election
          image: eu.gcr.io/jtgcp-subtitles/leader-elector:latest
          imagePullPolicy: Always
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "4040"
          args:
            - --lease-lock-name=electionlock
            - --lease-lock-namespace=default
            - --id=$(PODNAME)
            - --port=$(PORT)
            - --logtostderr=true
        - name: transcriber
          image: eu.gcr.io/jtgcp-subtitles/subtitling-transcribe:latest
          imagePullPolicy: Always
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "4040"
          args:
            - --redisHost=10.73.51.12
